# Generated by Django 5.1 on 2024-08-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEquipo', models.CharField(max_length=100)),
                ('modeloEquipo', models.CharField(max_length=100)),
                ('serialEquipo', models.CharField(max_length=100)),
                ('estadoOperatividad', models.CharField(max_length=100)),
                ('sistemaOperativo', models.CharField(max_length=100)),
                ('caracteristivas', models.CharField(max_length=500)),
                ('urlImagen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoSede',
            fields=[
                ('idEquipoSede', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'equipoSede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('idResponsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idSede', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSede', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('idTipoEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipoEquipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoEquipo',
                'managed': False,
            },
        ),
    ]
